package br.univates.jogovelha.view.historico;

import br.univates.alexandria.components.JFrameUtilsAdapter;
import javax.swing.JLabel;

/**
 * Painel que mostra o histórico das partidas que ocorreram
 * @author mateus.brambilla
 */
public class HistoricoPanel extends JFrameUtilsAdapter {

    /**
     * Creates new form HistoricoPanel
     */
    public HistoricoPanel() {
        initComponents();
    }
    
    // Getters
    public javax.swing.JTable getTabela() {
        return this.tabela;
    }
    
    public br.univates.jogovelha.view.components.JogadorComboBox getJogadorCb() {
        return this.jogadorComboBox1;
    }

    public JLabel getLabelTitulo() {
        return labelTitulo;
    }
    
    // Setters
    public void adicionarAcaoBotaoVoltar(java.awt.event.ActionListener listener) {
        this.botaoVoltar.addActionListener(listener);
    }
    
    public void hideVoltarBotao() {
        this.botaoVoltar.setVisible(false);
    }
    
    public void showVoltarBotao() {
        this.botaoVoltar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jogadorComboBox1 = new br.univates.jogovelha.view.components.JogadorComboBox();
        labelCb = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();

        labelTitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Partidas");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        labelCb.setLabelFor(jogadorComboBox1);
        labelCb.setText("Jogador");
        labelCb.setToolTipText("");

        botaoVoltar.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jogadorComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCb)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoVoltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogadorComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoVoltar)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private br.univates.jogovelha.view.components.JogadorComboBox jogadorComboBox1;
    private javax.swing.JLabel labelCb;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
