package br.univates.jogovelha.view.partida;

import br.univates.alexandria.components.JFrameUtilsAdapter;
import br.univates.jogovelha.view.components.TabuleiroItemPanel;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 * Tabuleiro com 9 botões clicáveis
 * @author mateus.brambilla
 */
public class JTabuleiro extends JFrameUtilsAdapter {
    private TabuleiroItemPanel[][] botoes;

    /**
     * Creates new form JTabuleiro
     */
    public JTabuleiro() {
        initComponents();
        setLayout(new GridLayout(3, 3));
        
        // Adicionando botões que representam as posições
        botoes = new TabuleiroItemPanel[3][3];
        
        Color corBorda = Color.BLACK;
        int espBorda = 2;
        
        for (int linha = 0; linha < botoes.length; linha++) {
            for (int coluna = 0; coluna < botoes[linha].length; coluna++) {
                botoes[linha][coluna] = new TabuleiroItemPanel();

                // Bordas
                int bordaBaixo = (linha < 2) ? espBorda : 0;
                int bordaDireita = (coluna < 2) ? espBorda : 0;

                Border bordaCustomizada = BorderFactory.createMatteBorder(
                    0, 0, bordaBaixo, bordaDireita, corBorda
                );

                botoes[linha][coluna].setBorder(bordaCustomizada);
                botoes[linha][coluna].setLinha(linha);
                botoes[linha][coluna].setColuna(coluna);

                add(botoes[linha][coluna]);
            }
        }
    }
    
    /**
     * Adiciona um ActionListener para um painel específico do tabuleiro.
     * O TabuleiroController usará isso.
     */
    public void adicionarAcaoBotao(int linha, int col, ActionListener listener) {
        this.botoes[linha][col].addActionListener(listener);
    }
    
    /**
     * Desenha o símbolo ('X' ou 'O') no painel especificado.
     * @param linha A linha (0-2)
     * @param col A coluna (0-2)
     * @param simbolo O símbolo ('X' ou 'O')
     */
    public void desenharSimbolo(int linha, int col, char simbolo) {
        if (linha >= 0 && linha < 3 && col >= 0 && col < 3) {
            this.botoes[linha][col].setSimbolo(simbolo);
        }
    }
    
    /**
     * Desabilita todos os painéis do tabuleiro (para o fim do jogo).
     */
    public void desabilitarTabuleiro() {
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                this.botoes[i][j].setEnabled(false);
            }
        }
    }

    /**
     * Reseta o tabuleiro para um novo jogo.
     */
    public void resetarTabuleiro() {
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                this.botoes[i][j].setSimbolo(' ');
                this.botoes[i][j].setEnabled(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
