package br.univates.jogovelha.view.partida;

import br.univates.alexandria.components.JFrameUtilsAdapter;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 * Painel que contém o tabuleiro, nomes dos jogadores e placar
 * É o container geral do jogo
 * @author mateus.brambilla
 */
public class PainelTabuleiro extends JFrameUtilsAdapter {

    /**
     * Creates new form PainelTabuleiro
     */
    public PainelTabuleiro() {
        initComponents();
    }
    
    //Getters
    public JButton getBotaoRevanche() {
        return botaoRevanche;
    }

    public JButton getBotaoVoltar() {
        return botaoVoltar;
    }

    public JTabuleiro getjTabuleiro1() {
        return jTabuleiro1;
    }

    public JLabel getJogador1() {
        return jogador1;
    }

    public JLabel getJogador2() {
        return jogador2;
    }

    public JLabel getPontuacaoJ1() {
        return pontuacaoJ1;
    }

    public JLabel getPontuacaoJ2() {
        return pontuacaoJ2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabuleiro1 = new br.univates.jogovelha.view.partida.JTabuleiro();
        botaoVoltar = new javax.swing.JButton();
        botaoRevanche = new javax.swing.JButton();
        jogador1 = new javax.swing.JLabel();
        jogador2 = new javax.swing.JLabel();
        pontuacaoJ1 = new javax.swing.JLabel();
        pontuacaoJ2 = new javax.swing.JLabel();

        jTabuleiro1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botaoVoltar.setText("Voltar");

        botaoRevanche.setText("Revanche");

        jogador1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jogador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jogador1.setText("Jogador 1");

        jogador2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jogador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jogador2.setText("Jogador 2");

        pontuacaoJ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pontuacaoJ1.setText("0");

        pontuacaoJ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pontuacaoJ2.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jogador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jogador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pontuacaoJ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(pontuacaoJ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jTabuleiro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoRevanche)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jogador1)
                    .addComponent(jogador2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pontuacaoJ1)
                    .addComponent(pontuacaoJ2))
                .addGap(18, 18, 18)
                .addComponent(jTabuleiro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar)
                    .addComponent(botaoRevanche))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoRevanche;
    private javax.swing.JButton botaoVoltar;
    private br.univates.jogovelha.view.partida.JTabuleiro jTabuleiro1;
    private javax.swing.JLabel jogador1;
    private javax.swing.JLabel jogador2;
    private javax.swing.JLabel pontuacaoJ1;
    private javax.swing.JLabel pontuacaoJ2;
    // End of variables declaration//GEN-END:variables
}
