package br.univates.jogovelha.view.jogador;

import br.univates.alexandria.components.JFrameUtilsAdapter;
import javax.swing.JButton;

/**
 * Tela responsável pelo cadastro de usuários
 * @author mateus.brambilla
 */
public class PainelCadastroUsuario extends JFrameUtilsAdapter {

    public PainelCadastroUsuario() {
        initComponents();
    }
    
    // Getters
    public br.univates.alexandria.components.textfield.JCpfField getCpf() {
        return textCpf;
    }
    
    public javax.swing.JTextPane getEndereco() {
        return textEndereco;
    }
    
    public br.univates.alexandria.components.textfield.JOnlyTextField getNome() {
        return textNome;
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public void adicionarAcaoBotao(java.awt.event.ActionListener listener) {
        this.botao.addActionListener(listener);
    }
    
    // Setters
    public void adicionarAcaoBotaoVoltar(java.awt.event.ActionListener listener) {
        this.botaoVoltar.addActionListener(listener);
    }
    
    public void hideVoltarBotao() {
        this.botaoVoltar.setVisible(false);
    }
    
    public void showVoltarBotao() {
        this.botaoVoltar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo1 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        labelEndereco = new javax.swing.JLabel();
        botao = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textEndereco = new javax.swing.JTextPane();
        try {
            textCpf = new br.univates.alexandria.components.textfield.JCpfField();
        } catch (java.text.ParseException e1) {
            e1.printStackTrace();
        }
        textNome = new br.univates.alexandria.components.textfield.JOnlyTextField();
        labelTitulo = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();

        labelTitulo1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelNome.setText("Nome Completo");

        labelCpf.setLabelFor(labelNome);
        labelCpf.setText("CPF");

        labelEndereco.setLabelFor(labelNome);
        labelEndereco.setText("Endereço");

        botao.setText("Cadastrar");

        jScrollPane2.setViewportView(textEndereco);

        labelTitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setLabelFor(this);
        labelTitulo.setText("Cadastro de Jogador");

        botaoVoltar.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botaoVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                    .addComponent(textNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(labelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(labelCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao)
                    .addComponent(botaoVoltar))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelTitulo)
                    .addContainerGap(172, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTitulo1;
    private br.univates.alexandria.components.textfield.JCpfField textCpf;
    private javax.swing.JTextPane textEndereco;
    private br.univates.alexandria.components.textfield.JOnlyTextField textNome;
    // End of variables declaration//GEN-END:variables
}
