package br.univates.jogovelha.view.jogador;

import br.univates.alexandria.components.JFrameUtilsAdapter;

/**
 * Painel destinado à visualização de todos usuários cadastrados
 * @author mateus.brambilla
 */
public class PainelVisualizarUsuarios extends JFrameUtilsAdapter {

    public PainelVisualizarUsuarios() {
        initComponents();
    }
    
    // Getter
    public javax.swing.JTable getTable() {
        return this.tableUsers;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloCadastroCorrentista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsers = new javax.swing.JTable();

        labelTituloCadastroCorrentista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTituloCadastroCorrentista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloCadastroCorrentista.setText("Correntistas Cadastrados");

        jScrollPane1.setViewportView(tableUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTituloCadastroCorrentista, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloCadastroCorrentista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTituloCadastroCorrentista;
    private javax.swing.JTable tableUsers;
    // End of variables declaration//GEN-END:variables
}
