package br.univates.jogovelha.view;

import br.univates.alexandria.util.Messages;

/**
 * Tela que agrega todas as telas fragmentadas anteriores
 * @author mateus.brambilla
 */
public class FramePrincipal extends javax.swing.JFrame {
    
    public FramePrincipal() {        
        initComponents();  
    }
    
    public void exibirErro(String mensagem) {
        Messages.errorMessage(this, mensagem);
    }
    
    public void exibirSucesso(String mensagem) {
        Messages.sucessMessage(this, mensagem);
    }
    
    // Getters
    public javax.swing.JPanel getPainelPrincipal() {
        return this.painel;
    }

    // Getters para os Itens de Menu de Início
    public javax.swing.JMenuItem getPaginaInicialMenuItem() {
        return paginaInicialMenuItem;
    }
    
    public javax.swing.JMenuItem getSairMenuItem() {
        return sairMenuItem;
    }

    // Getters para os Itens de Menu Jogador
    public javax.swing.JMenuItem getCadastroJogadorMenuItem() {
        return cadastroJogadorMenuItem;
    }

    public javax.swing.JMenuItem getVisualizarJogadorsMenuItem() {
        return visualizarJogadoresMenuItem;
    }

    public javax.swing.JMenuItem getEditarJogadorMenuItem() {
        return editarJogadorMenuItem;
    }
    
    public javax.swing.JMenuItem getDeletarJogadorMenuItem() {
        return deletarJogadorMenuItem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jogadorMenu = new javax.swing.JMenu();
        cadastroJogadorMenuItem = new javax.swing.JMenuItem();
        editarJogadorMenuItem = new javax.swing.JMenuItem();
        deletarJogadorMenuItem = new javax.swing.JMenuItem();
        visualizarJogadoresMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Velha");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        painel.setLayout(new java.awt.CardLayout());

        inicioMenu.setText("Início");

        inicioMenu.add(jSeparator1);

        paginaInicialMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        paginaInicialMenuItem.setText("Página Inicial");
        inicioMenu.add(paginaInicialMenuItem);

        sairMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        sairMenuItem.setText("Sair");
        inicioMenu.add(sairMenuItem);

        jMenuBar1.add(inicioMenu);

        jogadorMenu.setText("Correntista");

        cadastroJogadorMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cadastroJogadorMenuItem.setText("Cadastro");
        jogadorMenu.add(cadastroJogadorMenuItem);

        editarJogadorMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        editarJogadorMenuItem.setText("Editar");
        jogadorMenu.add(editarJogadorMenuItem);

        deletarJogadorMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        deletarJogadorMenuItem.setText("Deletar");
        jogadorMenu.add(deletarJogadorMenuItem);

        visualizarJogadoresMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        visualizarJogadoresMenuItem.setText("Visualizar");
        jogadorMenu.add(visualizarJogadoresMenuItem);

        jMenuBar1.add(jogadorMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FramePrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu inicioMenu;
    private javax.swing.JMenuItem cadastroJogadorMenuItem;
    private javax.swing.JMenu jogadorMenu;
    private javax.swing.JMenuItem deletarJogadorMenuItem;
    private javax.swing.JMenuItem editarJogadorMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem paginaInicialMenuItem;
    private javax.swing.JPanel painel;
    private javax.swing.JMenuItem sairMenuItem;
    private javax.swing.JMenuItem visualizarJogadoresMenuItem;
    // End of variables declaration//GEN-END:variables
}
