package br.univates.jogovelha.view;

import br.univates.alexandria.util.Messages;
import javax.swing.JMenuItem;

/**
 * Frame principal da aplicação, contendo o painel com o card layout e o menu
 * @author mateus.brambilla
 */
public class FramePrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FramePrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public FramePrincipal() {
        initComponents();
    }
    
    public void exibirErro(String mensagem) {
        Messages.errorMessage(this, mensagem);
    }
    
    public void exibirSucesso(String mensagem) {
        Messages.sucessMessage(this, mensagem);
    }

    // Getters
    public javax.swing.JPanel getPainelPrincipal() {
        return this.panel;
    }

    public JMenuItem getCadastrarUserMenuItem() {
        return cadastrarUserMenuItem;
    }

    public JMenuItem getIniciarJogoMenuItem() {
        return iniciarJogoMenuItem;
    }

    public JMenuItem getPainelInicialMenuItem() {
        return painelInicialMenuItem;
    }

    public JMenuItem getPartidasMenuItem() {
        return partidasMenuItem;
    }

    public JMenuItem getSairMenuItem() {
        return sairMenuItem;
    }

    public JMenuItem getVisualizarUserMenuItem() {
        return visualizarUserMenuItem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        iniciarJogoMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        painelInicialMenuItem = new javax.swing.JMenuItem();
        sairMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cadastrarUserMenuItem = new javax.swing.JMenuItem();
        visualizarUserMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        partidasMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("#3emLinha - Jogo da Velha Java");

        panel.setLayout(new java.awt.CardLayout());

        jMenu1.setText("Início");

        iniciarJogoMenuItem.setText("Iniciar Jogo");
        jMenu1.add(iniciarJogoMenuItem);
        jMenu1.add(jSeparator1);

        painelInicialMenuItem.setText("Painel Inicial");
        jMenu1.add(painelInicialMenuItem);

        sairMenuItem.setText("Sair");
        jMenu1.add(sairMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Jogador");

        cadastrarUserMenuItem.setText("Cadastrar");
        jMenu2.add(cadastrarUserMenuItem);

        visualizarUserMenuItem.setText("Visualizar");
        jMenu2.add(visualizarUserMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Histórico");

        partidasMenuItem.setText("Partidas");
        jMenu3.add(partidasMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FramePrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarUserMenuItem;
    private javax.swing.JMenuItem iniciarJogoMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem painelInicialMenuItem;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem partidasMenuItem;
    private javax.swing.JMenuItem sairMenuItem;
    private javax.swing.JMenuItem visualizarUserMenuItem;
    // End of variables declaration//GEN-END:variables
}
